<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ObatSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama' => 'Paracetamol 500mg',
                'image' => null,
                'deskripsi' => 'Obat penurun panas dan pereda nyeri.',
                'stok' => 100,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 1500,
                'harga_eceran' => 2500,
                'active' => true,
            ],
            [
                'nama' => 'Amoxicillin 500mg',
                'image' => null,
                'deskripsi' => 'Antibiotik untuk infeksi bakteri.',
                'stok' => 80,
                'expired_at' => Carbon::now()->addMonths(12),
                'harga_reseller' => 2000,
                'harga_eceran' => 3500,
                'active' => true,
            ],
            [
                'nama' => 'Vitamin C 500mg',
                'image' => null,
                'deskripsi' => 'Suplemen vitamin C untuk daya tahan tubuh.',
                'stok' => 150,
                'expired_at' => Carbon::now()->addMonths(24),
                'harga_reseller' => 1200,
                'harga_eceran' => 2500,
                'active' => true,
            ],
            [
                'nama' => 'Ibuprofen 400mg',
                'image' => null,
                'deskripsi' => 'Obat antiinflamasi dan pereda nyeri.',
                'stok' => 70,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 2500,
                'harga_eceran' => 4000,
                'active' => true,
            ],
            [
                'nama' => 'Cetirizine 10mg',
                'image' => null,
                'deskripsi' => 'Obat antihistamin untuk alergi.',
                'stok' => 120,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 1500,
                'harga_eceran' => 3000,
                'active' => true,
            ],
            [
                'nama' => 'Omeprazole 20mg',
                'image' => null,
                'deskripsi' => 'Obat untuk mengurangi asam lambung.',
                'stok' => 90,
                'expired_at' => Carbon::now()->addMonths(20),
                'harga_reseller' => 2500,
                'harga_eceran' => 4500,
                'active' => true,
            ],
            [
                'nama' => 'Loperamide 2mg',
                'image' => null,
                'deskripsi' => 'Obat untuk mengatasi diare.',
                'stok' => 60,
                'expired_at' => Carbon::now()->addMonths(14),
                'harga_reseller' => 1200,
                'harga_eceran' => 2500,
                'active' => true,
            ],
            [
                'nama' => 'Antasida Tablet',
                'image' => null,
                'deskripsi' => 'Obat untuk sakit maag dan asam lambung.',
                'stok' => 100,
                'expired_at' => Carbon::now()->addMonths(16),
                'harga_reseller' => 1000,
                'harga_eceran' => 2000,
                'active' => true,
            ],
            [
                'nama' => 'Salbutamol 2mg',
                'image' => null,
                'deskripsi' => 'Obat untuk asma dan gangguan pernapasan.',
                'stok' => 50,
                'expired_at' => Carbon::now()->addMonths(15),
                'harga_reseller' => 1800,
                'harga_eceran' => 3500,
                'active' => true,
            ],
            [
                'nama' => 'Chlorpheniramine Maleate (CTM)',
                'image' => null,
                'deskripsi' => 'Obat antihistamin untuk pilek dan alergi.',
                'stok' => 200,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 500,
                'harga_eceran' => 1500,
                'active' => true,
            ],
            [
                'nama' => 'Metformin 500mg',
                'image' => null,
                'deskripsi' => 'Obat untuk diabetes melitus tipe 2.',
                'stok' => 100,
                'expired_at' => Carbon::now()->addMonths(20),
                'harga_reseller' => 1500,
                'harga_eceran' => 3000,
                'active' => true,
            ],
            [
                'nama' => 'Amlodipine 5mg',
                'image' => null,
                'deskripsi' => 'Obat untuk hipertensi.',
                'stok' => 70,
                'expired_at' => Carbon::now()->addMonths(22),
                'harga_reseller' => 2000,
                'harga_eceran' => 3500,
                'active' => true,
            ],
            [
                'nama' => 'Simvastatin 20mg',
                'image' => null,
                'deskripsi' => 'Obat untuk menurunkan kolesterol.',
                'stok' => 80,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 2200,
                'harga_eceran' => 4000,
                'active' => true,
            ],
            [
                'nama' => 'Ranitidine 150mg',
                'image' => null,
                'deskripsi' => 'Obat untuk asam lambung.',
                'stok' => 60,
                'expired_at' => Carbon::now()->addMonths(14),
                'harga_reseller' => 1800,
                'harga_eceran' => 3200,
                'active' => true,
            ],
            [
                'nama' => 'Diazepam 2mg',
                'image' => null,
                'deskripsi' => 'Obat penenang dan anti cemas.',
                'stok' => 40,
                'expired_at' => Carbon::now()->addMonths(12),
                'harga_reseller' => 2500,
                'harga_eceran' => 5000,
                'active' => true,
            ],
            [
                'nama' => 'Albendazole 400mg',
                'image' => null,
                'deskripsi' => 'Obat cacing.',
                'stok' => 150,
                'expired_at' => Carbon::now()->addMonths(24),
                'harga_reseller' => 1200,
                'harga_eceran' => 2500,
                'active' => true,
            ],
            [
                'nama' => 'Captopril 25mg',
                'image' => null,
                'deskripsi' => 'Obat untuk hipertensi.',
                'stok' => 90,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 1000,
                'harga_eceran' => 2200,
                'active' => true,
            ],
            [
                'nama' => 'Prednison 5mg',
                'image' => null,
                'deskripsi' => 'Obat kortikosteroid untuk peradangan.',
                'stok' => 80,
                'expired_at' => Carbon::now()->addMonths(16),
                'harga_reseller' => 1500,
                'harga_eceran' => 3000,
                'active' => true,
            ],
            [
                'nama' => 'Asam Mefenamat 500mg',
                'image' => null,
                'deskripsi' => 'Obat pereda nyeri dan antiinflamasi.',
                'stok' => 100,
                'expired_at' => Carbon::now()->addMonths(18),
                'harga_reseller' => 2000,
                'harga_eceran' => 3500,
                'active' => true,
            ],
            [
                'nama' => 'Hydrocortisone Cream 1%',
                'image' => null,
                'deskripsi' => 'Salep untuk peradangan kulit.',
                'stok' => 50,
                'expired_at' => Carbon::now()->addMonths(12),
                'harga_reseller' => 5000,
                'harga_eceran' => 8500,
                'active' => true,
            ],
        ];

        DB::table('obat')->insert($data);
    }
}
